### ISSUE TITLE
Share crashes the app

### ISSUE THREAD

**Issue by colinkiama** [UWPCommunity/Quick-Pad#382] opened 2020-02-24 19:49 UTC
**Describe the bug**
The app crashes after attempting to use the "share" feature

**To Reproduce**
1. Go to 'File'
2. Click on 'Share'
3. App will load the share dialog for a bit then eventually crash

**Expected behavior**
The share dialog being opened, showing share targets

**Desktop (please complete the following information):**
 - OS Version: Windows 10 1909 18363.657
 - App version: v4.4.1.0

**Comment by yaichenbaum** [comment] 2020-02-24 20:40
@colinkiama Thank you for reporting this bug. I was able to reproduce the bug multiple times.

**Comment by diligamer** [comment] 2020-02-26 06:38
Mine crashes on bootup of app.

**Comment by yaichenbaum** [comment] 2020-02-26 14:25
@diligamer Try resetting the app.

**Comment by Jonatz** [comment] 2020-02-29 15:46
@diligamer @yaichenbaum I'm on 4.4.1.0. My app crashes on launch, too. Resetting and reinstalling didn't resolve the issue. I'm not sure how to give you log files or crash reports.

**Comment by yaichenbaum** [comment] 2020-03-01 01:19
@Jonatz Can you check Event Viewer?

**Comment by sharpninja** [comment] 2020-03-01 01:30
What is you Windows build?
________________________________

**Comment by Jonatz** [comment] 2020-03-01 09:08
@yaichenbaum @sharpninja My to PCs are on 18363.693. I pastetd the event protocol in XML below. I used Event Viewer for the first time, I hope, this is the right one.

- <Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
- <System>
  <Provider Name="Application Error" /> 
  <EventID Qualifiers="0">1000</EventID> 
  <Level>2</Level> 
  <Task>100</Task> 
  <Keywords>0x80000000000000</Keywords> 
  <TimeCreated SystemTime="2020-03-01T08:55:48.550140000Z" /> 
  <EventRecordID>36576</EventRecordID> 
  <Channel>Application</Channel> 
  <Computer>J-PC</Computer> 
  <Security /> 
  </System>
- <EventData>
  <Data>QuickPad.UI.exe</Data> 
  <Data>1.0.0.0</Data> 
  <Data>5e52b263</Data> 
  <Data>SharedLibrary.dll</Data> 
  <Data>2.2.27912.0</Data> 
  <Data>5d27c65c</Data> 
  <Data>00001007</Data> 
  <Data>00000000007e36ae</Data> 
  <Data>4f48</Data> 
  <Data>01d5efa7330e5d96</Data> 
  <Data>C:\Program Files\WindowsApps\49306atecsolution.QuickPad_4.4.1.0_x64__et10x9a9vyk8t\QuickPad.UI.exe</Data> 
  <Data>C:\Program Files\WindowsApps\Microsoft.NET.Native.Framework.2.2_2.2.27912.0_x64__8wekyb3d8bbwe\SharedLibrary.dll</Data> 
  <Data>8bdc84c0-ec18-4ee3-817f-2f861d3ab304</Data> 
  <Data>49306atecsolution.QuickPad_4.4.1.0_x64__et10x9a9vyk8t</Data> 
  <Data>App</Data> 
  </EventData>
  </Event>

**Comment by sharpninja** [comment] 2020-03-01 13:36
That’s a pretty old build of Windows.  Any chance of you updating?

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by Jonatz** [comment] 2020-03-01 13:41
@sharpninja I'm sorry, it seems to be the latest public release of 1909. https://en.wikipedia.org/wiki/Windows_10_version_history#Version_1909_(November_2019_Update)

**Comment by sharpninja** [comment] 2020-03-01 13:48
OK, let me think on it.

**Comment by yaichenbaum** [comment] 2020-03-01 15:10
I have gotten one other report of someone running into this same issue. Is the crash every single time you open Quick Pad, or only some of the times?

**Comment by Jonatz** [comment] 2020-03-01 15:30
@yaichenbaum It occurs on every launch on both devices. Since this first had emerged, I couldn't use the app.

**Comment by yaichenbaum** [comment] 2020-03-01 15:32
Can you try resetting the app using the Windows 10 settings app? There was a small change that caused some users to need to reset the app that way after updating to 4.3.9.0.

**Comment by Jonatz** [comment] 2020-03-01 16:29
@yaichenbaum I reset the app via Settings but this wouldn't resolve the issue.

**Comment by yaichenbaum** [comment] 2020-03-01 16:30
@Jonatz Are you use an ARM device?

**Comment by Jonatz** [comment] 2020-03-01 16:31
@yaichenbaum No, one is a custom desktop PC and the other one is a Surface Pro 5

**Comment by yaichenbaum** [comment] 2020-03-01 16:32
@Jonatz Can you try to clear out the folders for Quick Pad in the WindowsApps folder?

**Comment by Jonatz** [comment] 2020-03-02 12:03
@yaichenbaum After uninstalling the app, I can't find any QuickPad folders in my WindowsApps folder. I screenshotted the folders before unistalling (see below)
<img width="405" alt="Snipaste_2020-03-02_13-00-58" src="https://user-images.githubusercontent.com/17417041/75674775-1c655f00-5c86-11ea-9deb-2751a9c5098a.png">

**Comment by yaichenbaum** [comment] 2020-03-02 13:42
@Jonatz This is really strange. I understand if you don't want to do this but to help me get to the bottom of this issue would you be able to try running the app from the source code?

**Comment by Jonatz** [comment] 2020-03-02 13:47
@yaichenbaum I'd be glad to help. Please understand that it will take me a little time because I wrote my last line of C# code four years ago (oh, the WP8 halcyon days) and Visual Studio is not even installed on my system.

**Comment by yaichenbaum** [comment] 2020-03-02 13:48
@Jonatz I really appreciate this. I understand it will take time but I hope it helps us figure out what went wrong. Please let me know if you need any help getting it set up.

**Comment by yaichenbaum** [comment] 2020-04-17 01:55
This issue has been fixed with 24fd2ff06d48836981cfcb669e4fb001df531117.

**Closed by yaichenbaum** 2020-04-17 01:55 UTC
Labels: bug, critical
