### ISSUE TITLE
Things to fix with QuickPad.UI

### ISSUE THREAD

**Issue by yaichenbaum** [UWPCommunity/Quick-Pad#334] opened 2020-01-19 19:30 UTC
- [x] Opening a txt file makes the app think IsDirty is true.
- [x] Sometimes opening a file from file explorer shows the splash screen and then just crashes the app.

**Comment by sharpninja** [comment] 2020-01-20 00:26
> Going to the font settings page freezes the app

I cannot reproduce this problem.  Please trigger this in VS and then pause the debugger to see where it's freezing.

**Comment by sharpninja** [comment] 2020-01-20 05:11
Commited to SharpNinja-Uno branch.  Please pull and test.

**Comment by yaichenbaum** [comment] 2020-01-20 05:54
@sharpninja in the future please don't check off the list until I finish testing, what I suggest is telling me when you something is fixed so I can test and then I will check it off 🙂

**Comment by sharpninja** [comment] 2020-01-20 16:52
> @sharpninja in the future please don't check off the list until I finish testing, what I suggest is telling me when something is fixed so I can test it and then I will check it off 🙂

No problem.  Might be good to put two text boxes, the first for "I'm Done' and the second for "Tested".

**Comment by sharpninja** [comment] 2020-01-20 16:53
> IsDirty is set to true after opening rtf files (I am not sure why this is happening since we are setting it to false as soon as the file loads)

I specifically fixed that last night.  Please validate.

**Comment by sharpninja** [comment] 2020-01-20 16:53
> The app crashes if I type anything (only when no file is open) 

Cannot reproduce

**Comment by sharpninja** [comment] 2020-01-20 16:54
> The default font color setting isn't working

Please be more specific.  What is it doing wrong?

**Comment by sharpninja** [comment] 2020-01-20 16:55
> Changing the default font color or from the font color drop down doesn't seem to affect the font color

As designed?  What is the expected action and behavior?

**Comment by yaichenbaum** [comment] 2020-01-20 18:52
@sharpninja this is for you to check off items on
- [ ] Changing the font color setting and reopening the app makes any text you type white.
- [ ] Set the default file mode to rtf, open Quick Pad, anything you type is white.
- [ ] Changing the font and font size in rtf mode isn't working
- [ ] The buttons on the toolbar are not updating based on the cursor position in rtf mode.
- [ ] Default font options for rtf mode are not being followed when opening the app in rtf mode.
- [ ] Default font options for txt mode are not being followed when opening the app in txt mode.

**Comment by sharpninja** [comment] 2020-01-21 05:38
> Changing the font color setting and reopening the app makes any text you type white.

[ ] RTF
[ ] Text
[ ] Both?

**Comment by sharpninja** [comment] 2020-01-21 07:21
> Set the default file mode to rtf, open Quick Pad, anything you type is white.

Without the default color selector this shouldn't be anything I can do anything about.

**Comment by yaichenbaum** [comment] 2020-01-21 14:39
@sharpninja 
![image](https://user-images.githubusercontent.com/39923744/72813714-d2726d80-3c31-11ea-8f7a-3c0de86d5ff4.png)
I am often getting this crash the first time opening the app after changing a setting.

**Comment by yaichenbaum** [comment] 2020-01-21 14:42
> ~> Changing the font color setting and reopening the app makes any text you type white.~
> 
> The color selector has been removed from settings. I'm assuming this is no longer an issue?

This is still an issue in txt mode, we need to set the color ourselves depending on if its a light or dark theme.

**Comment by sharpninja** [comment] 2020-01-22 21:27
> If you have a sentence in RTF mode with two different font sizes and select it then they all become the same size

Ugh, ok.  This would be because when you select the range I get the font size for the range from the Document.  Of course, there can be only a single value, so it then see that may be different than what was there previously and so then it sets the backing value to the new value, which causes the SelectedItem to change in the font size box which triggers setting the font size of the range, which then applies it to the whole range.

Same thing is happening with Font.

So, I guess we won't update the command bar for Font and Font Size when the selection changes.

**Comment by sharpninja** [comment] 2020-02-01 13:27
> Opening an RTF file with Quick Pad from within Files Explorer doesn't load the correct colors of the text. 

I cannot reproduce this.  In the Assets folder there is a test RTF file.  Right click on it in Explorer and select Open With -> Quick Pad.  The colors come up correctly.

**Comment by sharpninja** [comment] 2020-02-01 13:31
> Text is always white in light theme in rtf mode

Text must have a color assigned to it in RTF.  If a document is created in a theme that uses a light font then the baseline text is the light font.  Changing the theme does not change the default font color of the RTF file unless you apply the color to the RichEditBox.  However, doing so will override ALL font colors in the document.

I really, really, really believe that we should force the RichEditBox to always have a white background and black text by default, regardless of the chosen theme.  These things do not apply to the TextEdit control because it doesn't matter what color is assigned to text because it is not specified in the document.

**Comment by sharpninja** [comment] 2020-02-01 13:51
I have fixed not being able to save.

**Comment by yaichenbaum** [comment] 2020-02-02 00:32
@sharpninja we went through this before about forcing a white background, this would ruin dark theme. All that needs to be done is assign a color based on the theme. A dark theme gets a white forecolor and a light theme gets a black forecolor.

**Comment by yaichenbaum** [comment] 2020-02-02 00:33
> Opening an RTF file with Quick Pad from within Files Explorer doesn't load the correct colors of the text.

This is specifically when there is more then one color in the rtf file.

**Comment by sharpninja** [comment] 2020-02-03 16:21
This happens consistently in Windows 1909 and manifests as a crash of NTDLL.DLL due to a memory access fault.  It does not happen on 20H1.

**Closed** 2020-02-12 22:04 UTC
Labels: bug
