### ISSUE TITLE
Support for more encoding types

### ISSUE THREAD

**Issue by yaichenbaum** [UWPCommunity/Quick-Pad#107] opened 2019-08-30 14:57 UTC
We should add support for both saving and reading these files.
- [x] UTF-16 LE
- [x] UTF-16 BE
- [x] UTF-8
- [x] UTS-8 with BOM

![image](https://user-images.githubusercontent.com/39923744/64030610-ea2b4700-cb14-11e9-8a45-78cf5425d9dc.png)

**Comment by dmarciano** [comment] 2019-11-07 18:43
I was looking at the code to see what this would take and from what I see, files are saved using the Storage.Pickers.FileSavePicker and Storage.StorageFile classes, but they don't see to have an Encoding property for this to be specified.

Would a new, custom, Save As window be created to support this feature?

**Comment by yaichenbaum** [comment] 2019-11-07 18:50
I would like to use whatever controls are default to the Universal Windows Platform. I don't even know how to go about this and probably won't have time to work on it for a while but I was thinking about having an option in settings if the user wanted to use a different encoding.
Something along the lines of whats being done in Notepads, but instead of radio buttons I would use a combo box.
![image](https://user-images.githubusercontent.com/39923744/68418096-99177f00-0165-11ea-8f33-b5c5045406a8.png)

**Comment by dmarciano** [comment] 2019-11-07 19:10
From what I've found, there is no way to do it directly from the Save As dialog.  So your suggestion about a settings menu would probably be easier than creating a whole separate Save As Dialog.

The actually saving it pretty easy, but takes slight reworking.  Unlike other version of .NET where you can simply specify the encoding directly in the stream, it would need to be done like so:

1. Get the encoding specified by the user (e.g. from the settings)
2. Use the Encoding class (with the properly selected encoding) to get the bytes of the text
3. Finally, instead of doing FileIO.WriteTextAsync, a stream would be created from the StorageFile and the raw bytes writen.

Reading the file can be a little trickier, because UTF-8 doesn't require a BOM.  So the best thing to do would be to force a BOM to **always** be written, regarless if it is required or not, so ensure that their is no ambiguity in the encoding.  With this, the Fallback Decoding would not be necessary.  If the user is opening a file without a BOM, it should automatically be considered UTF-8.

**Comment by yaichenbaum** [comment] 2019-11-07 19:15
Thank you for writing this all down, I am not very familiar with how to do this but I will definitely try in few months from now when I have some time to work on it. It is possible someone else will do it before I even get a chance to try but I won't complain 😂.

**Comment by dmarciano** [comment] 2019-11-07 19:21
I am willing to give it a chance.  I have a lot of experience but not with UWP apps.  From everything I read though, it seems like it would be relatively simple, since it only has to do specifically with reading/writing the bytes.

I am working on getting the app running on my computer (I had to install all the UWP stuff, emulators, etc.) but if I get it going I will definitely give it at shot.  I didn't see any contributing guidelines so I thought I would ask about this issue here first.  If I get it running, and can work on it, should I just fork this repo from the dev branch to do the work and, once completed, submit the PR?

**Comment by yaichenbaum** [comment] 2019-11-07 19:24
Wow, that would be a major help. If you need any help getting set up let me know. This project is run mainly by enthusiasts like me and there are not any guidelines to follow other then being respectful of everyone.
All you need to do is fork the repo and work off the dev branch. When you are done then you can open a pull request and I or another contributor will review the PR and make sure it doesn't conflict mess anything up.

**Comment by dmarciano** [comment] 2019-11-07 19:32
I was able to actually get it working and running on my computer so I will fork it and work on this issue.

I did find one, minor, thing but it is a UI issue.  When you change the text in the file, a star * is shown before the name.  If you go to save, and then click Cancel (i.e. the file is **not* saved) the star is still removed from the beginning of the "New Document" title so it looks like the file was actually saved.

I will see about fixing this issue as well while I implement the other stuff.  I figured this is soooo minor that it doesn't warrent its own thread and/or PR.

I will keep you posted.

**Comment by yaichenbaum** [comment] 2019-11-07 19:33
Good catch, whatever works for you in terms of creating separate issues or PR's, however just make sure to create a summery of changes in the PR.

**Comment by dmarciano** [comment] 2019-11-07 19:34
Of course

**Comment by dmarciano** [comment] 2019-11-07 21:20
Okay...so I got to actually use the code and so far this is the plan:

1. I've updated the Settings pane with a new combo box to choose the default encoding.  The options are UTF-8, UTF-16 LE, UTF-16 BE, and UTF-32.  These were chosen because they are the built-in encoding enum types so we don't have to handle any special cases or look up specific code page numbers.  There is also ASCII (UTF-7) but that is fully compatible with UTF-8.  I already have the new setting saving and able to be migrated.

2. The FileStorage class does not have a way specify the encoding of the data.  Therefore, a new file storage class will be derived from this one so that the encoding information can be saved along with the other file information.  This way, when a file is saved multiple times, we can just look at this new property and know what encoding was used and re-use it easily with the file stream

Therefore, at this time, I am actively working on this issue and hope to have a PR for it by the EOD tomorrow or Monday (the latest) barring any unexpected issues.

**Comment by yaichenbaum** [comment] 2019-11-07 21:22
Nice! I am really looking forward. @Leisvan when the PR is ready, would you be able to look it over?

**Comment by Leisvan** [comment] 2019-11-08 08:11
Sure. Please let me know when the PR is ready. I may miss it otherwise.

**Comment by dmarciano** [comment] 2019-11-08 14:13
The PR should be ready in about an hour or less.  I have a few more tests to run, but so far everything seems to working.  I created files in Notepad and saved them a UTF-8, UTF-8 BOM, UTF-16 BE, and UTF-16 LE.  I confirmed that when the application opened these files, the correct encoding was detected and the text was loaded.

I also confirmed that the autosaving, and updating the file, worked, and that the proper encoding was maintained by re-opening the file in the application (and checking the encoding that was detected) as well as opening it in Notepad and ensure that application still saw the correct encoding as well.

I am going to run a few more test with new files created directly in the application and ensure that both the application and Notepad see the correct encoding and that it is maintained when saving/re-opening.  If everything goes smoothly, I will it will be ready for review.  I will keep you posted.

**Comment by yaichenbaum** [comment] 2019-11-08 14:15
@dmarciano Sounds great! Do you think we should have it display the encoding in the status bar? Idea shown bellow
![image](https://user-images.githubusercontent.com/39923744/68482823-5e1a5780-0208-11ea-8d28-e13d04186bc1.png)

**Comment by dmarciano** [comment] 2019-11-08 15:01
@yaichenbaum I am not the greatest with UI design, however I have added a textblock at the lower right had corner of the window.  When the application first starts, it shows the default encoding (the one set in the settings).  However, once a file is open, this value is updated to the encoding of the currently selected file.  If a new file is created, it goes back to the default settings.

Everything else seems to be working.  I've been able to created multiple files in various encodings, open/close them with the app and Notepad, and then re-open/update/re-saved/re-open without an issues.  I am going to push the commit to the forked repo now and then do the pull request.  You should have it in less than 30 minutes.

**Comment by yaichenbaum** [comment] 2019-11-08 15:06
The design is something I can go over if its not how I like it, but it sounds like you have everything covered.

**Comment by dmarciano** [comment] 2019-11-08 15:17
@Leisvan  @yaichenbaum The PR has been completed.  Let me know if you need anything else from me or if you find any issues.

**Comment by yaichenbaum** [comment] 2019-11-08 15:31
Thank you so much for your help and offer to do more, I don't think there is anything else at the moment but I will let you know if there are any issues with the PR.

**Comment by Leisvan** [comment] 2019-11-08 18:33
I can't get to a computer until Monday. Run the tests needed and I'll review it by then. Good work @dmarciano 👍

**Comment by yaichenbaum** [comment] 2019-11-11 20:39
@dmarciano thanks you so much for your help on this feature!

**Comment by Leisvan** [comment] 2019-11-11 20:49
Good work @dmarciano . This works really well. If you are committed to this feature I'd recommend you use [UDE.CSharp.UWP](https://www.nuget.org/packages/UDE.CSharp.UWP), a port of Mozilla Charset Detector. With this tool, you'll be able to provide most of `System.Text.Encoding` supported encodings. If you need help in this matter you can reach me at any time. Again, Good Work!

**Comment by dmarciano** [comment] 2019-11-12 13:12
@Leisvan I took at that library and thought of a couple things that would have to be resolved before it could be implemented:

1. Does the text control being used support all System.Text.Encoding formats?
2. If so, opening and saving the file in the same encoding would be easy enough, however would it even be feasible to give a user a choice of all possible encodings.  I don't know off hand how many there actually are, but I would assume it would be more than could reasonably fit into a dropdown box.

**Comment by Leisvan** [comment] 2019-11-12 13:51
1. After you encode the text you'll have an "interpreted" string. The RichEditBox will handle it normally.
2. That's not a problem. Even if it were 50 a Combobox would handle it just fine. What's really important, I think, is to support all of them to include other writing systems into the app.

**Comment by yaichenbaum** [comment] 2019-11-12 14:14
@Leisvan How many are you currently supporting in Notes Sheet?

**Comment by Leisvan** [comment] 2019-11-12 15:47
Can't check right now. About 20+

**Comment by sharpninja** [comment] 2019-11-20 22:03
These encodings are now supported:

- Utf8
- Utf16Be
- Utf16Le
- Utf32Be
- Utf32Le
- ASCII

**Closed by sharpninja** 2019-11-20 22:03 UTC
Labels: enhancement
